# Generated by Django 4.2.7 on 2026-04-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('icon', models.CharField(default='🏆', help_text='Emoji icon', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Name', max_length=100)),
                ('role', models.CharField(default='Developer', max_length=200)),
                ('bio', models.TextField(blank=True, default='A passionate developer who loves building things.')),
                ('college', models.CharField(blank=True, default='Your College', max_length=200)),
                ('email', models.EmailField(blank=True, default='you@example.com', max_length=254)),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com/in/yourprofile')),
                ('github_username', models.CharField(default='Kishan0507', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
